apiVersion: v1
kind: Pod
metadata:
 name: pod-example
spec:
  containers:
  - name: my-nginx
    image: nginx

#     apiVersion: v1
# kind: Pod
# metadata:
#   name: nginx
# spec:
#   containers:
#   - name: nginx
#     image: nginx:1.14.2
#     ports:
#     - containerPort: 80