apiVersion: v1
kind: Pod
metadata:
  name: env
  labels:
    about: environment-variables
  annotations:
    owner: "pavan"
    course: "Devops"
spec:
  containers:
  - name: environment
    image: nginx
    env:
    - name: course
      value: devops
    - name: trainer
      value: siva
    - name: duration
      value: "120hours"